--Employee details & employee salary Project--


CREATE TABLE Emp_personal_details
(EMPLOYEEID INT,
EMPLOYEE_NAME VARCHAR(50),
EMPLOYEE_GENDER VARCHAR(20),
EMPLOYEE_AGE INT,
EMPLOYEE_COUNTRY VARCHAR(50)
);

INSERT INTO Emp_personal_details
(11001,'Pavan','MALE',26,'INDIA'),
(11002,'Guptha', 'MALE',28,'INDIA'),
(11003,'SUMITH S','MALE',32,'INDIA'),
(11004,'MUNNA DAS','MALE',35,'INDIA'),
(11005,'DEVI KUMARI','FEMALE',29,'INDIA'),
(11006,'Roopa','FEMALE',33,'LONDON'),
(11007,'MAHESH','MALE',29,'INDIA'),
(11008,'RAMA P','MALE',22,'USA'),
(1109,'NEHA M','FEMALE',31,'UK'),
(11010,'Jannat','FEMALE',29,'LONDON');

CREATE TABLE Emp_work_details
(EMPLOYEEID INT,
EMPLOYEE_DEPT VARCHAR(60),
EMPLOYEE_DATE_OF_JOINING DATE,
EMPLOYEE_SALARY INT
);

INSERT INTO Emp_work_details VALUES
(11001,'WEBSITE','2022-12-01',25000),
(11002,'ENGINEER','2022-12-01',27000),
(11003,'DEVELOPER','2022-12-02',30000),
(11004,'DATA ANALYST','2022-12-05',33000),
(11005,'ANALYST','2022-12-06',23000),
(11006,'BI ANALYST','2022-12-06',33000),
(11007,'POWER BI DEVELOPER','2022-12-12',42000),
(11008,'DATA ANALYSIS','2022-12-15',44000),
(11009,'DATA ANALYTICS','2022-12-19',450000),
(11010,'POWER BI ADMIN','2022-12-25',620000);


SELECT * FROM Emp_personal_details;

SELECT * FROM Emp_work_details;

SELECT EMPLOYEEID,
       EMPLOYEE_NAME,
	   EMPLOYEE_GENDER,
	   EMPLOYEE_AGE,
	   EMPLOYEE_COUNTRY
FROM Emp_personal_details;

SELECT EMPLOYEEID,
      EMPLOYEE_DEPT,
	  EMPLOYEE_DATE_OF_JOINING,
	  EMPLOYEE_SALARY
FROM Emp_work_details;

SELECT TOP 5* FROM Emp_personal_details;

SELECT TOP 4* FROM Emp_personal_details;

SELECT TOP 2* FROM Emp_personal_details;

SELECT TOP 3* FROM Emp_personal_details;

SELECT DISTINCT(EMPLOYEE_NAME)
FROM Emp_personal_details;

SELECT DISTINCT(EMPLOYEE_DEPT)
FROM Emp_work_details;

SELECT DISTINCT(EMPLOYEE_COUNTRY)
FROM Emp_personal_details;

SELECT COUNT(EMPLOYEE_NAME)
FROM Emp_personal_details;

SELECT COUNT(EMPLOYEE_DEPT)
FROM Emp_work_details;

SELECT COUNT(EMPLOYEE_DEPT) AS DEPT
FROM Emp_work_details;

SELECT SUM(EMPLOYEE_SALARY) AS TOTAL_SALARY
FROM Emp_work_details;

SELECT AVG(EMPLOYEE_SALARY) AS AVG_SALARY
FROM Emp_work_details;

SELECT MAX(EMPLOYEE_SALARY) AS MAX_SALARY
FROM Emp_work_details;

SELECT MIN(EMPLOYEE_SALARY) AS MIN_SALARY
FROM Emp_work_details;

SELECT * FROM Emp_personal_details
WHERE EMPLOYEE_NAME = 'SUMITH S';

SELECT * FROM Emp_personal_details
WHERE EMPLOYEE_NAME IN ('RAMA P','DEVI KUMARI');

SELECT * FROM Emp_personal_details
WHERE EMPLOYEE_COUNTRY = 'INDIA';

SELECT * FROM Emp_work_details
WHERE EMPLOYEE_COUNTRY = 'UK';

SELECT * FROM Emp_personal_details
WHERE EMPLOYEE_COUNTRY IN ('LONDON','USA');

SELECT * FROM Emp_work_details
WHERE EMPLOYEEID = 11005;

SELECT * FROM Emp_work_details
WHERE EMPLOYEEID IN ('11005','11006','11010');

SELECT * FROM Emp_work_details
WHERE EMPLOYEE_DEPT = 'ENGINEER';

SELECT * FROM Emp_work_details
WHERE EMPLOYEE_DEPT = 'DATA ANALYST';

SELECT * FROM Emp_work_details
WHERE EMPLOYEE_DEPT IN ('DEVELOPER','DATA ANALYTICS','POWER BI ADMIN');

SELECT * FROM Emp_personal_details
WHERE EMPLOYEE_AGE < 25;

SELECT * FROM Emp_personal_details
WHERE EMPLOYEE_AGE <= 25;

SELECT * FROM Emp_personal_details
WHERE EMPLOYEE_AGE >= 25;

SELECT * FROM Emp_personal_details
WHERE EMPLOYEE_AGE > 30;

SELECT * FROM Emp_personal_details
WHERE EMPLOYEE_AGE <> 30;

SELECT * FROM Emp_work_details
WHERE EMPLOYEE_AGE < 25 AND EMPLOYEE_GENDER = 'MALE';

SELECT * FROM Emp_personal_details
WHERE EMPLOYEE_AGE > 30 AND EMPLOYEE_GENDER IN ('MALE','FEMALE');

SELECT * FROM Emp_personal_details
WHERE EMPLOYEE_AGE <> 28 AND EMPLOYEE_GENDER IN ('MALE','FEMALE');

SELECT * FROM Emp_work_details
WHERE EMPLOYEE_DEPT IN('ANALYST','POWER BI DEVELOPER','DATA ANALYST');

SELECT * FROM Emp_work_details
WHERE EMPLOYEE_DATE_OF_JOINING = '2022-12-01';

SELECT * FROM Emp_work_details
WHERE EMPLOYEE_SALARY > 25000;

SELECT * FROM Emp_work_details
WHERE EMPLOYEE_SALARY > 25000 AND EMPLOYEE_DEPT = 'DEVELOPER';

SELECT * FROM Emp_work_details
WHERE EMPLOYEE_SALARY >= 25000 AND EMPLOYEE_DEPT = 'POWER BI DEVELOPER';

SELECT * FROM Emp_work_details
WHERE EMPLOYEE_SALARY >= 25000 AND EMPLOYEE_DEPT IN ('POWER BI DEVELOPER', 'ENGINEER','DEVELOPER');

SELECT * FROM Emp_work_details
WHERE EMPLOYEE_SALARY <= 30000 AND EMPLOYEE_DEPT IN ('POWER BI DEVELOPER', 'ENGINEER','DEVELOPER');

SELECT * FROM Emp_personal_details
WHERE EMPLOYEE_NAME LIKE 'S%';

SELECT * FROM Emp_personal_details
WHERE EMPLOYEE_NAME LIKE '%A%';

SELECT * FROM Emp_personal_details
WHERE EMPLOYEE_NAME LIKE '%U';

SELECT EMPLOYEE_GENDER,COUNT(*) AS GEN
FROM Emp_personal_details
GROUP BY EMPLOYEE_GENDER;

SELECT EMPLOYEE_DEPT, COUNT(*) AS DEPT
FROM Emp_work_details
GROUP BY EMPLOYEE_DEPT;

SELECT EMPLOYEE_DEPT,COUNT(*) AS DEPT
FROM Emp_work_details
WHERE EMPLOYEE_SALARY >= 32000
GROUP BY EMPLOYEE_DEPT
ORDER BY DEPT;

SELECT * FROM Emp_personal_details
ORDER BY EMPLOYEE_NAME;

SELECT * FROM Emp_personal_details
ORDER BY EMPLOYEE_NAME DESC;

SELECT EMPLOYEE_NAME ,COUNT(EMPLOYEE_NAME) AS 'FULL NAME'
       FROM Emp_personal_details
WHERE EMPLOYEE_AGE > 25
GROUP BY EMPLOYEE_NAME
ORDER BY 'FULL NAME';


SELECT * FROM Emp_personal_details;
SELECT * FROM Emp_work_details;

INSERT INTO Emp_personal_details VALUES
(11011,'MAHI S','FEMALE',25,'INDIA'),
(11012,'NULL','NULL',25,'CHINA'),
(NULL,'SURESH A','MALE',NULL,'LONDON');

INSERT INTO Emp_work_details VALUES
(11011,'ENGINEER','2022-12-29',24000),
(NULL,'POWER BI','2022-12-28',260000),
(11013,'DATA ANALYST','2022-12-31',22000);


SELECT * FROM Emp_personal_details
JOIN
EMPLOYEE_SALARY ON
Emp_personal_details.EMPLOYEEID = Emp_work_details.EMPLOYEEID;


SELECT * FROM Emp_personal_details A
JOIN
Emp_work_details B ON
A.EMPLOYEEID = B.EMPLOYEEID;

SELECT EMPLOYEE_NAME, EMPLOYEE_GENDER,EMPLOYEE_DEPT,EMPLOYEE_SALARY
FROM Emp_personal_details A
JOIN
Emp_work_details B ON
A.EMPLOYEEID = B.EMPLOYEEID;

SELECT EMPLOYEE_NAME, EMPLOYEE_GENDER,EMPLOYEE_DEPT,EMPLOYEE_SALARY
FROM Emp_personal_details A
LEFT JOIN
Emp_work_details B ON
A.EMPLOYEEID = B.EMPLOYEEID;

SELECT EMPLOYEE_NAME, EMPLOYEE_GENDER,EMPLOYEE_DEPT,EMPLOYEE_SALARY
FROM Emp_personal_details A
RIGHT JOIN
Emp_work_details B ON
A.EMPLOYEEID = B.EMPLOYEEID;

SELECT EMPLOYEE_NAME, EMPLOYEE_GENDER,EMPLOYEE_DEPT,EMPLOYEE_SALARY
FROM Emp_personal_details A
FULL OUTER JOIN
Emp_work_details B ON
A.EMPLOYEEID = B.EMPLOYEEID;


SELECT SUM(Emp_work_details) AS 'SUM SALARY'
FROM EMPLOYEE_SALARY;

SELECT AVG(Emp_work_details) AS 'AVG SALARY'
FROM EMPLOYEE_SALARY;

SELECT MAX(Emp_work_details) AS 'MAX SALARY'
FROM EMPLOYEE_SALARY;

SELECT MIN(Emp_work_details) AS 'MIN SALARY'
FROM EMPLOYEE_SALARY;

SELECT EMPLOYEE_NAME,EMPLOYEE_DEPT,SUM(EMPLOYEE_SALARY) AS 'TOTAL SALARY'
FROM Emp_work_details
JOIN
Emp_personal_details ON 
Emp_work_details.EMPLOYEEID = Emp_personal_details.EMPLOYEEID
GROUP BY EMPLOYEE_NAME,EMPLOYEE_DEPT;

SELECT EMPLOYEE_NAME,EMPLOYEE_DEPT,AVG(EMPLOYEE_SALARY) AS 'AVG SALARY'
FROM Emp_work_details
JOIN
Emp_personal_details ON 
Emp_work_details.EMPLOYEEID = Emp_personal_details.EMPLOYEEID
GROUP BY EMPLOYEE_NAME,EMPLOYEE_DEPT


